openapi: 3.0.1
info:
  title: Apollo
  description: my api
  contact:
    name: Raise issue
    url: https://github.com/GMOD/Apollo3Server/issues
    email: nathandunn@lbl.gov
  license:
    name: Apache 2.0
    url: http://foo.bar
  version: 3.0.0
paths:
  /organism/organism/deleteOrganism:
    post:
      summary: Remove an organism
      operationId: deleteOrganism
      parameters: []
      requestBody:
        description: Organism to delete
        content:
          application/json: {}
        required: true
      responses:
        default:
          content:
            application/json: {}
